- src/main/java/io/hops/transaction/context/TransactionsStats.java
- src/main/java/io/hops/transaction/lock/Lock.java
Support Memcache Stats
Add a switch to enable/disable detailed stats logging
> Move setPartitionKey switch from Lock to BaseINodeLock

- src/main/java/io/hops/metadata/hdfs/entity/INode.java
Fixed Performance Issures with dir listing
> Fixed Performance Issures with dir listing

- src/main/java/io/hops/metadata/hdfs/dal/INodeDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/ProjectedINode.java
fixed file size problem sith subtree operations
> moved to NDB 7.4.7. Fixed filesize issues with STOs

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/LeaseDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/LeasePathDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/LeasePath.java
- src/main/java/io/hops/metadata/hdfs/entity/SubTreeOperation.java
Do not read INodeAttr.. in dir listing as it is not needed
Fixed bugs
> Chmod and chown are STO operations

- src/main/java/io/hops/DalNdbEventStreaming.java
preparation for hopshadoop/hops-metadata-dal-impl-ndb#28
> Include streaming library

- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/entity/AppSchedulingInfo.java
- src/main/java/io/hops/util/HopsWorksHelper.java
Add columns to yarn_appschedulinginfo in order to display application status in the user interface.
> Add column for hopsworks

- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/dal/ResourceRequestOfContainerDataAccess.java
- src/main/java/io/hops/metadata/yarn/entity/ResourceRequest.java
https://issues.apache.org/jira/secure/attachment/12655718/Yarn-1408.11.patch
> YARN-1408 with resourceRequest recovered

- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/dal/ContainersCheckPointsDataAccess.java
- src/main/java/io/hops/metadata/yarn/dal/YarnHistoryPriceDataAccess.java
- src/main/java/io/hops/metadata/yarn/dal/YarnRunningPriceDataAccess.java
- src/main/java/io/hops/metadata/yarn/entity/ContainerCheckPoint.java
- src/main/java/io/hops/metadata/yarn/entity/ContainersLogs.java
- src/main/java/io/hops/metadata/yarn/entity/YarnHistoryPrice.java
- src/main/java/io/hops/metadata/yarn/entity/YarnProjectsDailyCost.java
- src/main/java/io/hops/metadata/yarn/entity/YarnProjectsQuota.java
- src/main/java/io/hops/metadata/yarn/entity/YarnRunningPrice.java
Add mechanism to persist informations relative to the uber pricing system.
Preparation for: hopshadoop/hops#257
> Price fixer

- src/main/java/io/hops/metadata/yarn/entity/RMNodeComps.java
preparation for hopshadoop/hops #259
> Distribut token management

- src/main/java/io/hops/StorageConnector.java
add a -format option to the resourcemanager that format only the yarn tables in the db
preparation for:
hopshadoop/hops#263
hopshadoop/hops-metadata-dal-impl-ndb#55
> Yarn formating

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/MetadataLogEntry.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
Use timestamps instead of logicaltime
> Added INode ParentId and Name to hdfs_metadata_log

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/LeasePath.java
- src/main/java/io/hops/transaction/lock/Lock.java
added last_block_id and penultimate_block_id to leasepath
> Fixes HOPS-17

- src/main/java/io/hops/exception/UniqueKeyConstraintViolationException.java
UniqueKeyConstraintViolationException is a transient exception
> Fixes HOPS-51

- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/dal/ContainerToDecreaseDataAccess.java
- src/main/java/io/hops/metadata/yarn/dal/ContainerToSignalDataAccess.java
- src/main/java/io/hops/metadata/yarn/dal/RMNodeApplicationsDataAccess.java
- src/main/java/io/hops/metadata/yarn/dal/ReservationStateDataAccess.java
- src/main/java/io/hops/metadata/yarn/entity/Container.java
- src/main/java/io/hops/metadata/yarn/entity/ContainerToSignal.java
- src/main/java/io/hops/metadata/yarn/entity/RMNodeApplication.java
- src/main/java/io/hops/metadata/yarn/entity/ReservationState.java
https://hopshadoop.atlassian.net/browse/HOPS-65
> [HOPS-65] update to follow hadoop 2.8.2 updates

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/INodeDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeBase.java
- src/main/java/io/hops/metadata/hdfs/entity/MetadataLogEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/ProjectedINode.java
https://hopshadoop.atlassian.net/browse/HOPS-97
> [HOPS-97] Use logical time per inode instead of timestamp for ordering

- pom.xml
- src/main/java/io/hops/DalDriver.java
- src/main/java/io/hops/DalEventStreaming.java
Also corrected names, to not call it ndb when it is not ndb dependent.
https://hopshadoop.atlassian.net/browse/HOPS-127
> [HOPS-127] change pom to deploy snapshot on snapshot repository.

- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/entity/quota/ProjectDailyCost.java
https://hopshadoop.atlassian.net/browse/HOPS-149
> [HOPS-149] add application IDs in project daily cost

- .github/pull_request_template.md
https://hopshadoop.atlassian.net/browse/HOPS-159
> [HOPS-159] Add PR template

- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/BlockInfoDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/ExcessReplicaDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/InvalidateBlockDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/ReplicaUnderConstructionDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/StorageDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/CorruptReplica.java
- src/main/java/io/hops/metadata/hdfs/entity/ExcessReplica.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeBase.java
- src/main/java/io/hops/metadata/hdfs/entity/InvalidatedBlock.java
- src/main/java/io/hops/metadata/hdfs/entity/ProjectedINode.java
- src/main/java/io/hops/metadata/hdfs/entity/ReplicaBase.java
- src/main/java/io/hops/metadata/hdfs/entity/Storage.java
- src/main/java/io/hops/transaction/context/BaseEntityContext.java
https://hopshadoop.atlassian.net/browse/HOPS-86
New feature
Work done mostly by bcleenders, implementing necessary database suport to port the following HDFS jiras and all the corresponding sub jiras to hops:
- HDFS-2832
- HDFS-5682
- HDFS-6702
No
hopshadoop/hops-metadata-dal-impl-ndb#119
hopshadoop/hops#429
> [HOPS-86] Heterogeneous storage

- src/main/java/io/hops/metadata/hdfs/entity/EncodingStatus.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeIdentifier.java
https://hopshadoop.atlassian.net/browse/HOPS-188
> [HOPS-188] apply HDFS-4209

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/ReplicaUnderConstruction.java
https://hopshadoop.atlassian.net/browse/HOPS-197
> [HOPS-197] apply HDFS-4721

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
https://hopshadoop.atlassian.net/browse/HOPS-246
> [HOPS-246] apply HDFS-4772

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/RetryCacheEntryDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/RetryCacheEntry.java
- src/main/java/io/hops/transaction/lock/Lock.java
https://hopshadoop.atlassian.net/browse/HOPS-281
> [HOPS-281] apply HDFS-5025

- src/main/java/io/hops/transaction/EntityManager.java
- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-322
> [HOPS-322] correct LightWeightRequestHandler

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/PendingBlockDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/PendingBlockInfo.java
https://hopshadoop.atlassian.net/browse/HOPS-305
> [HOPS-305] apply HDFS-5020

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/AceDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/Ace.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeBase.java
- src/main/java/io/hops/metadata/hdfs/entity/ProjectedINode.java
- src/main/java/io/hops/transaction/lock/Lock.java
https://hopshadoop.atlassian.net/browse/HOPS-5
Feature: Adding extended acls to HopsFS
See design document: "Hops ACLs" and eventually readthedocs in the ACLs section
> [HOPS-5] Hops ACLs.

- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-365
> [HOPS-365] NullPointerException when trying to role back transaction

- src/main/java/io/hops/metadata/common/entity/Variable.java
https://hopshadoop.atlassian.net/browse/HOPS-397
> [HOPS-397] change enum order in Variable

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/CorruptReplica.java
- src/main/java/io/hops/metadata/hdfs/entity/ReplicaUnderConstruction.java
https://hopshadoop.atlassian.net/browse/HOPS-399
> [HOPS-399] apply HDFS-5438

- src/main/java/io/hops/metadata/hdfs/entity/HashBucket.java
https://hopshadoop.atlassian.net/browse/HOPS-405
refactoring
> [HOPS-405] Block Report Refactoring.

- src/main/java/io/hops/util/Slicer.java
https://hopshadoop.atlassian.net/browse/HOPS-484
> [HOPS-484] multythread slicer

- src/main/java/io/hops/metadata/hdfs/dal/BlockInfoDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-480
> [HOPS-480] replace full table scan by primary key operation

- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-505
Tests result here: https://bbc1.sics.se/jenkins/view/gautier/job/hops-gautier-maven/3/testReport/
> [HOPS-505] fix LightWeightRequestHandler not rolling back.

- src/main/java/io/hops/metadata/election/entity/LeDescriptor.java
- src/main/java/io/hops/metadata/hdfs/dal/INodeDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/OngoingSubTreeOpsDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-477
bug fix 
> [HOPS-477] Added GC for STO locks left by dead namenodes

- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/CacheDirectiveDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/CachePoolDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/CachedBlockDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/CacheDirective.java
- src/main/java/io/hops/metadata/hdfs/entity/CachePool.java
- src/main/java/io/hops/metadata/hdfs/entity/CachedBlock.java
- src/main/java/io/hops/metadata/hdfs/entity/RetryCacheEntry.java
- src/main/java/io/hops/transaction/lock/Lock.java
https://hopshadoop.atlassian.net/browse/HOPS-598
> [HOPS-598] apply HDFS-4949

- src/main/java/io/hops/metadata/hdfs/entity/MetadataLogEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/ProjectedINode.java
https://hopshadoop.atlassian.net/browse/HOPS-610
> [HOPS-610] Add rename and setOwner as events in metadata_log

- src/main/java/io/hops/metadata/hdfs/dal/EncodingStatusDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/INodeDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/EncodingStatus.java
https://hopshadoop.atlassian.net/browse/HOPS-625
Bug fix
Block are removed in batch instead of one by one
> [HOPS-625] batch blocks removal

- src/main/java/io/hops/metadata/hdfs/dal/BlockLookUpDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-628
performance fix
improve replicas removal efficiency.
> [HOPS-628] make the replicas removal more efficient.

- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/CorruptReplicaDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/MisReplicatedRange.java
https://hopshadoop.atlassian.net/browse/HOPS-632
> [HOPS-632] apply HDFS-5535

- src/main/java/io/hops/metadata/hdfs/dal/ExcessReplicaDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-654
Bug fix
> [HOPS-654] get excess replica metric from DB

- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/ActiveBlockReportsDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/ActiveBlockReport.java
https://hopshadoop.atlassian.net/browse/HOPS-482
bug fix
> [HOPS-482] Block report load balancing

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
- src/main/java/io/hops/transaction/handler/AsyncLightWeightRequestHandler.java
- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
- src/main/java/io/hops/transaction/handler/RequestHandler.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-756
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-767
> [HOPS-756] and [HOPS-767]

- src/main/java/io/hops/StorageConnector.java
- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
- src/main/java/io/hops/util/Slicer.java
https://hopshadoop.atlassian.net/browse/HOPS-814
https://hopshadoop.atlassian.net/browse/HOPS-815
> [HOPS-814] and [HOPS-815]

- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
…nted.
https://hopshadoop.atlassian.net/browse/HOPS-800
improvement in logging
> [HOPS-800] Transaction nested diagnostic contexts is not properly printed

- src/main/java/io/hops/metadata/hdfs/dal/INodeDataAccess.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-806
> [HOPS-806] get max inode id

- src/main/java/io/hops/metadata/common/entity/Variable.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-848
> [HOPS-848] apply HDFS-6783

- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-867?filter=allopenissues
https://github.com/hopshadoop/hops/pull/593
> [HOPS-867] Fixing string equality

- src/main/java/io/hops/metadata/common/entity/LongVariable.java
https://hopshadoop.atlassian.net/browse/HOPS-890
> [HOPS-890] handle "casting" of IntVariable to LongVariable

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/UnderReplicatedBlockDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/UnderReplicatedBlock.java
https://hopshadoop.atlassian.net/browse/HOPS-958
> [HOPS-958] apply HDFS-7165

- src/main/java/io/hops/transaction/handler/RequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1010
update
improved logging
no
No need to run tests just merge it. All of the three projects have been updated
> [HOPS-1010] Removing useless logs that are printed at INFO loggin level

- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1045
Bug fix
> [HOPS-1045] Fix bug with LockUpgradeException logging

- src/main/java/io/hops/metadata/hdfs/dal/ActiveBlockReportsDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-1100
> [HOPS-1100] BRTrackingService.assignWork in one transaction.

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/DirectoryWithQuotaFeatureDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/BlockInfo.java
- src/main/java/io/hops/metadata/hdfs/entity/DirectoryWithQuotaFeature.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeBase.java
- src/main/java/io/hops/metadata/hdfs/entity/QuotaUpdate.java
https://hopshadoop.atlassian.net/browse/HOPS-1146
https://hopshadoop.atlassian.net/browse/HOPS-1158
> [HOPS-1146] and [HOPS-1158]

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/DirectoryWithQuotaFeature.java
- src/main/java/io/hops/metadata/hdfs/entity/QuotaUpdate.java
> [HOPS-1168] HDFS-7775

- src/main/java/io/hops/metadata/yarn/dal/rmstatestore/ApplicationAttemptStateDataAccess.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1216
Bug fix
> [HOPS-1216] fix Tupple does not exist when deleting application attempts

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/QuotaUpdate.java
https://hopshadoop.atlassian.net/browse/HOPS-1215?filter=-1
> [HOPS-1215] Set storage type for Small Files stored in the database

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/ActiveBlockReport.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1214
> [HOPS-1214] Blockreport load balancing per NN

- src/main/java/io/hops/metadata/hdfs/entity/INodeIdentifier.java
https://hopshadoop.atlassian.net/browse/HOPS-1320
Bug fix
Speed up adding blocks during block reporting and avoid ongoing block report overwriting forced block report trigger.
> [HOPS-1320] fix TestBalancer

- src/main/java/io/hops/exception/TransientDeadLockException.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1313
> [HOPS-1313] Suppress transient exceptions

- src/main/java/io/hops/metadata/hdfs/dal/ActiveBlockReportsDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/SafeBlocksDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-1360
https://hopshadoop.atlassian.net/browse/HOPS-1362
> [HOPS-1360] and [HOPS-1362]

- src/main/java/io/hops/metadata/hdfs/dal/DBFileDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-1351
> [HOPS-1351] Making small files size reconfigurable

- pom.xml
- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/ConfDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/ConfMutationDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/QuotaUpdate.java
- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/dal/rmstatestore/ApplicationAttemptStateDataAccess.java
- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1378
> [HOPS-1378] Move most of the codebase to hadoop 3.2.0

- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/dal/quota/ProjectQuotaDataAccess.java
- src/main/java/io/hops/metadata/yarn/dal/quota/ProjectsDailyCostDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-1385
> [HOPS-1385] redo the Yarn quota system for hadoop 3

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeBase.java
- src/main/java/io/hops/metadata/hdfs/entity/ProjectedINode.java
- src/main/java/io/hops/metadata/hdfs/entity/StoredXAttr.java
https://hopshadoop.atlassian.net/browse/HOPS-1434
https://hopshadoop.atlassian.net/browse/HOPS-1451
> [HOPS-1434][HOPS-1451]

- src/main/java/io/hops/metadata/yarn/entity/RMNodeApplication.java
Found this while playing with bazel :D 
@berthoug
> [HOPS-1479] Fix incorrect RMNodeApplication.equals()

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/EncryptionZoneDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/EncryptionZone.java
- src/main/java/io/hops/metadata/hdfs/entity/StoredXAttr.java
- src/main/java/io/hops/transaction/lock/Lock.java
Merge the following jiras:
- HDFS-6134 and HADOOP-10150 subtasks
- HDFS-6954
- HDFS-6905
- HDFS-6986
- HDFS Credential Provider related Unit Test Failure
- HDFS-6951
- HDFS-6966
- HDFS-7061
- HDFS-7032
- HDFS-7006
- HDFS-6851
- HDFS-6843
- HDFS-7004
- HDFS-7047
- HDFS-6970
- HDFS-7115
- HDFS-7126
- HDFS-7078
- HDFS-6987.
- HDFS-7139
- HDFS-7138.
- HDFS-7077
- HDFS-7124
- HDFS-7179
- HDFS-7181
- HDFS-7209
- HDFS-7190
- HDFS-7252
- HDFS-6824.
- HDFS-7243.
- HDFS-6938
- HDFS-7536
- HDFS-7530
- HDFS-7718
- HDFS-8004
- HADOOP-11312
https://hopshadoop.atlassian.net/browse/HOPS-1501
new feature: encryption …
> [HOPS-1501] add encryption at rest feature

- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeMetadataLogEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/LeasePath.java
- src/main/java/io/hops/metadata/hdfs/entity/Replica.java
- src/main/java/io/hops/metadata/hdfs/entity/StoredXAttr.java
- src/main/java/io/hops/metadata/hdfs/entity/XAttrMetadataLogEntry.java
- src/main/java/io/hops/transaction/context/EntityContext.java
- src/main/java/io/hops/transaction/context/EntityContextStat.java
- src/main/java/io/hops/transaction/context/TransactionsStats.java
- src/main/java/io/hops/transaction/handler/RequestHandler.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1513
bug fix
> [HOPS-1513] Cleanup bad coding in metadata-dal

- src/main/java/io/hops/StorageConnector.java
https://hopshadoop.atlassian.net/browse/HOPS-1516
bug fix
> [HOPS-1516] remove prints to out

- .gitignore
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/FileProvXAttrBufferDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/FileProvenanceDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/FileProvXAttrBufferEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/FileProvenanceEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/INode.java
- src/main/java/io/hops/metadata/hdfs/entity/MetaStatus.java
- src/main/java/io/hops/metadata/yarn/TablesDef.java
- src/main/java/io/hops/metadata/yarn/dal/AppProvenanceDataAccess.java
- src/main/java/io/hops/metadata/yarn/entity/AppProvenanceEntry.java
https://hopshadoop.atlassian.net/browse/HOPS-1541
feature - provenance
Log filesystem operations into a log tailed by epipe
This JIRA has changes to the database (add tables)
> [HOPS-1541] provenance

- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
https://hopshadoop.atlassian.net/browse/HOPS-1556
> [HOPS-1556] Handling RuntimeException in TransactionRequestHandler class

- pom.xml
> HOPSWORKS-1765 archiva

- src/main/java/io/hops/transaction/lock/TransactionLockTypes.java
Fixed Bug in Delete STO
Fixed Bug in batch locking of multiple inodes
> [HOPS-1553] Fixed NNThroughput Benchmark

- src/main/java/io/hops/metadata/hdfs/dal/ReplicaUnderConstructionDataAccess.java
https://hopshadoop.atlassian.net/browse/HOPS-1564
> [HOPS-1564] Fixed bug in transaction cache

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/XAttrDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/FileProvXAttrBufferEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/FileProvenanceEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/INodeMetadataLogEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/MetadataLogEntry.java
- src/main/java/io/hops/metadata/hdfs/entity/StoredXAttr.java
- src/main/java/io/hops/metadata/hdfs/entity/XAttrMetadataLogEntry.java
https://hopshadoop.atlassian.net/browse/HOPS-1568
improvement
> [HOPS-1568] Add support for large XAttrs (>13500)

- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/LeaseCreationLocksDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/Lease.java
- src/main/java/io/hops/metadata/hdfs/entity/LeaseCreationLock.java
- src/main/java/io/hops/metadata/hdfs/entity/LeasePath.java
https://hopshadoop.atlassian.net/browse/HOPS-1573
https://hopshadoop.atlassian.net/browse/HOPS-1572
> [HOPS-1573] Fix garbage collection in Lease Paths

- pom.xml
- src/main/java/io/hops/metadata/common/entity/Variable.java
- src/main/java/io/hops/metadata/hdfs/TablesDef.java
- src/main/java/io/hops/metadata/hdfs/dal/ReplicaUnderConstructionDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/RetryCacheEntryDataAccess.java
- src/main/java/io/hops/metadata/hdfs/entity/RetryCacheEntry.java
> [HOPS-1571] Partition hdfs_retry_cache table

- src/main/java/io/hops/transaction/lock/TransactionLockTypes.java
> [HOPS-1590] Fixed lease manager for rename operations

- src/main/java/io/hops/metadata/hdfs/dal/BlockInfoDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/ExcessReplicaDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/INodeDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/InvalidateBlockDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/ReplicaDataAccess.java
- src/main/java/io/hops/metadata/hdfs/dal/ReplicaUnderConstructionDataAccess.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
> add ee changes that should also have been made in community

- src/main/java/io/hops/DalStorageFactory.java
> [HOPSWORKS-CLOUD-1598] Added direct mem and DB utilization to HopsFS UI

- src/main/java/io/hops/metadata/hdfs/dal/OngoingSubTreeOpsDataAccess.java
> [HOPSWORKS-CLOUD-1540] Fixing cleaning up subtree operations

- src/main/java/io/hops/StorageConnector.java
- src/main/java/io/hops/transaction/EntityManager.java
- src/main/java/io/hops/transaction/context/TransactionContext.java
- src/main/java/io/hops/transaction/handler/LightWeightRequestHandler.java
- src/main/java/io/hops/transaction/handler/TransactionalRequestHandler.java
> [HOPS-1654] Reconnect to NDB after network failure

- pom.xml
https://hopsworks.atlassian.net/browse/HOPSFS-47
> [HOPSFS-47] Bump version to 3.2.0.9-SNAPSHOT

- src/main/java/io/hops/metadata/common/entity/ArrayVariable.java
- src/main/java/io/hops/metadata/common/entity/ByteArrayVariable.java
- src/main/java/io/hops/metadata/common/entity/DoubleVariable.java
- src/main/java/io/hops/metadata/common/entity/IntVariable.java
- src/main/java/io/hops/metadata/common/entity/LongVariable.java
- src/main/java/io/hops/metadata/common/entity/StringVariable.java
- src/main/java/io/hops/metadata/common/entity/Variable.java
> Hopsfs 57 se

- pom.xml
> Hopsfs 110

- pom.xml
HOPSFS-159: Release 3.2.0.13-RC0
> HOPSFS-159: Release 3.2.0.13-RC0

- pom.xml
HOPSFS-160: Release 3.2.0.14-SNAPSHOT
> HOPSFS-160: Release 3.2.0.14-SNAPSHOT

- src/main/java/io/hops/metadata/hdfs/dal/RetryCacheEntryDataAccess.java
> HOPSFS-162: Fixed Retry Cache Cleaner

- pom.xml
HOPSFS-178: Release 3.2.0.15-SNAPSHOT
> HOPSFS-178: Release 3.2.0.15-SNAPSHOT

- pom.xml
HOPSFS-199: Release 3.2.0.15-RC0
> HOPSFS-199: Release 3.2.0.15-RC0

- pom.xml
HOPSFS-200: Release 3.2.0.16-SNAPSHOT
> HOPSFS-200: Release 3.2.0.16-SNAPSHOT
